name: My first workflow

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
     - name: Print message
       run: echo "Hello!!"

  say-bye:
    runs-on: ubuntu-latest

    steps: 
     - name: Print message
       run: echo "Byee!!"