# name: My first workflow

# on: push

# jobs:
#   say-hello:
#     runs-on: ubuntu-latest

#     steps:
#      - name: Print message
#        run: echo "Hello!!"

#   say-bye:
#     runs-on: ubuntu-latest

#     steps: 
#      - name: Print message
#        run: echo "Byee!!"





# name: My second workflow

# on: push

# jobs:
#   say-hello:
#     runs-on: ubuntu-latest

#     steps:
#      - name: Print message
#        run: echo "Hello!!"

#   say-bye:
#     needs: say-hello
#     runs-on: ubuntu-latest

#     steps: 
#      - name: Print message
#        run: echo "Byee!!"





name: Clone repo workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code //clone a repo
       uses: actions/checkout@v4 

     - name: list file
       run: ls

     - name: check version
       run: node -v