# name: My first workflow

# on: push

# jobs:
#   say-hello:
#     runs-on: ubuntu-latest

#     steps:
#      - name: Print message
#        run: echo "Hello!!"

#   say-bye:
#     runs-on: ubuntu-latest

#     steps: 
#      - name: Print message
#        run: echo "Byee!!"





# name: My second workflow

# on: push

# jobs:
#   say-hello:
#     runs-on: ubuntu-latest

#     steps:
#      - name: Print message
#        run: echo "Hello!!"

#   say-bye:
#     needs: say-hello
#     runs-on: ubuntu-latest

#     steps: 
#      - name: Print message
#        run: echo "Byee!!"





name: Clone repo workflow

on: push

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint


  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build


  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test


  deploy-app:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: node server.js